/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Interrupt' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "device_registers.h"

/* Keil::Device:Startup@2.0.0 */
#define RTE_DEVICE_STARTUP_S32K14x      /* Device Startup for S32K14x Series */


#endif /* RTE_COMPONENTS_H */
